puts "Example".object_id
puts "Example".object_id
puts "Example".object_id
puts "Example".object_id
puts "-----------------------"
puts :Example.object_id
puts :Example.object_id
puts :Example.object_id
puts :Example.object_id
