puts "Exemple".object_id
puts "Exemple".object_id
puts "Exemple".object_id
puts "Exemple".object_id
puts "-----------------------"
puts :Exemple.object_id
puts :Exemple.object_id
puts :Exemple.object_id
puts :Exemple.object_id